version: '3.6'
services:
  front:
    image: nginx
    container_name: front
    volumes:
    - "./src:/etc/nginx/templates"
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
    - "8081:8081"
